(*test_create.ml *)

open Test
open Test_main
   

let create_test (folder:string) (file:string) =
  let _ = print_endline folder in
  let file_a = Array.append [|" "|] [|file|] in 
  let (stat, s_out, s_err) = run folder file_a in
  let desc = "description (* This file was generated by uc-dsl test suite *) \n.\n" in
  let args = ("args:" ^ file) in
  let file_outcome =
    match stat with
    |Some 0 -> "success"
    |None -> "unknown"
    |Some n -> "failure" in
  let o_come =
    if (s_out = "") then (
      ("outcome: (*outcome autogenerated please verify for accuracy*) " ^ file_outcome ^"\n"^s_err ^"\n.\n"))
    else
      ("(* ***** Warning: std out is not empty ***** *)\n" ^"(* std out:"^s_out^"*)" ^"outcome: (*outcome autogenerated please verify *) " ^ file_outcome ^"\n"^s_err ^"\n.\n") in
  let _ =
    (* Write message to file *)
    let oc = open_out (folder^"/TEST") in    (* create or truncate file, return channel *)
    Printf.fprintf oc "%s" (desc^args^"\n"^o_come);   (* write something *)   
    close_out oc;
  in ()
      
let create_dir file folder =
  let _ =
    try Unix.mkdir folder 0o755
    with
    |Unix.Unix_error (e,_,_) -> (print_endline (Unix.error_message e); exit 1)
  in
  let _ =
    let ic = Str.split (Str.regexp "/") file in
    let file_to_write  = List.nth ic ((List.length ic)-1) in
    let _ = try
        Sys.command ("cp "^ file ^" "^folder^"/"^  file_to_write)
      with
      |Sys_error e -> (print_endline e; exit 1) in
    create_test folder file_to_write in
  ()

let make_dir file =
  let folder = String.sub file 0 (String.length file -3) in
  let (b: bool)  = 
    try
      Sys.is_directory folder(*; print_endline ("we are in try " ^ string_of_bool b)*)
    with
    |Sys_error e -> (let _ = print_endline e in false )
  in
  if (b) then (
    print_string (folder ^ " already exists, I cannot work with leftover files \n") ;
    exit 1)
  else create_dir file folder
  
let pre_walk dir =
  let _ =  print_endline ("we are at pre_walk"^dir^" \n") in
  let rec one_file filelist str =
    match filelist with
    |[] -> if str = "" then
             (print_endline "Success"; exit 0)
           else
             (print_endline "Completed with some issues"; print_endline str; exit 1)
    |e::l -> let _ = (* print_endline "we are at one_file" ;*)  make_dir e in one_file l str
  in
  try
    let (file_list, str) =  walk_directory_tree dir ".*uc$" in
    if List.length file_list = 0 then
      (print_endline "list is empty"; print_endline str; exit 1)
    else one_file file_list str
                                                      

  with
  |Sys_error e -> print_endline e; exit 1
                  
let pre_create dir log_file fail_log_file  =
  try
    let _ = Sys.is_directory(dir) in pre_walk dir
  with
  |Sys_error e -> try
                  let _ = Sys.is_directory ("./"^dir) in pre_walk ("./"^dir)
                with
                |Sys_error e -> (print_endline e;print_string (dir^" is not a valid directory \n"); exit 1)
